### PR TITLE
Update API for OpenSSL 3.0

### PR DESCRIPTION
**Pull request by catap**
Here a minor changes in OpenSSL API.

Fixes: https://github.com/avast/retdec/issues/1040

### CODE REVIEW

**Comment by s3rvac** [comment]
@PeterMatula Do we want to use OpenSSL 3.0 in `authenticode_parser` when (1) the rest of RetDec uses OpenSSL 1.x and (2) many systems only have OpenSSL 1.x?

**Comment by catap** [comment]
@s3rvac I feel that the right way is requires the same `OpenSSL` version everywhere. Right now it seems quite a mix. But I will wait of @PeterMatula response.

Anyway all another part of `retdec` is built fine with OpenSSL 3.

**Comment by catap** [comment]
From another hand I may easy add a few `ifdef` to make the code universal.

**Comment by catap** [comment]
Here it is. Right now it just introduced a compatibility with OpenSSL 3 without broken anything :)

**Comment by catap** [comment]
@s3rvac I feel that I've overstep all your concern, am I wrong?

**Comment by s3rvac** [comment]
Yes, thank you :slightly_smiling_face:. I will leave the review to @PeterMatula.

**Comment by catap** [comment]
@s3rvac / @PeterMatula I do also have a patch for version 4.0: https://github.com/catap/retdec/tree/openssl3-v4.0

Do you need as PR?

**Review by PeterMatula — APPROVED** [review]
Looks good, I will trigger tests and if they pass I will merge.

Btw, these sources in `deps` are in fact from here [avast/authenticode-parser](https://github.com/avast/authenticode-parser), but because we wanted to reduce the number of external deps, we decided to _"inline"_ this simple repo in RetDec directly. But not to worry, @HoundThe can you please integrate these changes back to [avast/authenticode-parser](https://github.com/avast/authenticode-parser)?

And a second task, @HoundThe can you look into the question of _"different OpenSSL versions"_ opened here? I would like to know, where (what other parts) are we using OpenSSL, which versions, and if they can all deal with OpenSSL 3.0.

**Comment by catap** [comment]
@PeterMatula thanks!

Anyway, I'd love to share with you that v4.0 can't be build on system which has installed OpenSSL 3.0. Yes, it ships OpenSSL but system one is also used to build it. When your system has 1.x it is working, but with 3.0 => the hell is here.

The way to fix it is trivial: https://github.com/catap/retdec/commit/6aa99feff5ea9290a0983633d26f8ad85fdae5ba

But it still, this patch need to be applied.

v4.0 also can't be build on Apple M1 because of embeded OpenSSL version which is too old.

And here I'd love to ask: maybe it is a good idea to release a new version?

**Pull request merged**
