### PR TITLE
Change procedure linkage table indirect calls to direct calls

### PR DESCRIPTION
**Pull request by richardlford**
When a function in an external dynamically-loaded library is
called, the call is made indirectly through the
procedure linkage table (PLT). The call into the PLT is
made with an ordinary call instruction, but in the PLT
there is a jump (not call) to the final destination.
In this situation retdec is not properly handling
the parameter passing. This change turns these indirect
calls into direct calls and deletes the PLT code.
This makes the result simpler and allows the parameters
to be properly passed.

### CODE REVIEW

**Comment by PeterMatula** [comment]
I will, before the end of this week.

**Comment by PeterMatula** [comment]
Thanks @richardlford, I think in general it looks good. Few regression tests are failing, but I reviewed the problems and it looks like it is nothing related to output quality regression. Most fails are due to some crash I will have to further investigate, and probably one or two are some minor details that were testing the layout before your changes.
I will try to fix the tests and let you know.

**Comment by richardlford** [comment]
> Few regression tests are failing, but I reviewed the problems and it looks like it is nothing related to output quality regression. Most fails are due to some crash I will have to further investigate, and probably one or two are some minor details that were testing the layout before your changes.
> I will try to fix the tests and let you know.

@PeterMatula, sorry, I should have run the tests first. I am now setting up to run the regression tests myself.

**Comment by richardlford** [comment]
@PeterMatula, I have investigated the crashes. In my code, after making the PLT calls direct I was deleting the PLT function. But that was causing problems related to virtual calls. When I don't delete the PLT function only 3 tests are failing and those are ones where my changes cause improvement, so the test will need to be adjusted. I expect to have a new commit early next week.

**Comment by richardlford** [comment]
@PeterMatula, I did decide to accomplish my goal in the param_return pass rather than with these changes. Since I don't use any of these changes I'm closing this pull request. I've created a new pull request, #1085. I've also created a pull request in the retdec-regressions-tests repo, https://github.com/avast/retdec-regression-tests/pull/117#issue-1297600973, to account for the effect of these changes.

**Pull request closed without merging**
