### PR TITLE
Try to fix issue #638

### PR DESCRIPTION
**Pull request by seviezhou**
Reference: https://github.com/avast/retdec/issues/638

### CODE REVIEW

**Comment by PeterMatula** [comment]
Maybe, lets Run TeamCity builds and see if everything is ok.

**Comment by s3rvac** [comment]
Not all TeamCity builds have been run. Let's run TeamCity builds again.

**Comment by s3rvac** [comment]
One of our regression tests started failing with the proposed fix:
```
[Step 5/6] integration.switch.Test_MSVC (switch-test-msvc-O0.ex)                  [ FAIL ]  (1.77s)
[Step 5/6] ...F
[Step 5/6] ======================================================================
[Step 5/6] FAIL: test_issue_636 (integration.switch.Test_MSVC)
[Step 5/6] ----------------------------------------------------------------------
[Step 5/6] Traceback (most recent call last):
[Step 5/6]   File "retdec-regression-tests\integration\switch\test.py", line 177, in test_issue_636
[Step 5/6]     assert self.out_c.contains('char \* g9; // 0x419548')
[Step 5/6] AssertionError
[Step 5/6]
[Step 5/6] ----------------------------------------------------------------------
[Step 5/6] Ran 4 tests in 0.108s
[Step 5/6]
[Step 5/6] FAILED (failures=1)
```
@PeterMatula, can you please take a look?

**Comment by PeterMatula** [comment]
The test is no longer failing. I diffed the before and after and found no obvious regression. It could possibly be solved more robustly, but the change makes sense and does some good. Thanks @seviezhou.

**Pull request merged**
