### PR TITLE
Retdec is a library now

### PR DESCRIPTION
**Pull request by PeterMatula**
Changes:
* implemented `retdec::decompile()` library function
* removed `retdec-decompiler.py`
* implemented new `retdec-decompiler` application
* removed `retdec-bin2llvmir` and `retdec-llvmir2hll`
* removed some helper python scripts
* refactored a bunch of things
* many more

### CODE REVIEW

**Comment by PeterMatula** [comment]
run tc tests

**Comment by PeterMatula** [comment]
run tc tests

**Comment by PeterMatula** [comment]
run tc tests

**Comment by PeterMatula** [comment]
run tc tests

**Comment by xkubov** [comment]
run tc tests

**Comment by PeterMatula** [comment]
run tc tests

**Comment by PeterMatula** [comment]
run tc tests

**Comment by silentguy256** [comment]
The manual is currently a bit confusing cause the main page shows the current readme (which talks about everything being executable) while the releases it links to are still in the old style that still needs python 3

**Pull request merged**
